const SC__ = require("scion-core");
const cycle = new SC__.Statechart(
    {
        id: 'CYCLE',
        states: [
            {
                id: 'Hungry_',
                onEntry: () => {
                    console.log("\tEntering 'Hungry?'... ");
                },
                onExit: () => {
                    console.log("\tExiting 'Hungry?'... ");
                },
                transitions: [
                    {
                        event: 'go!',
                        target: 'Replete_'
                    }
                ]
            },
            {
                id: 'Replete_',
                onEntry: () => {
                    console.log("\tEntering 'Replete?'... ");
                },
                onExit: () => {
                    console.log("\tExiting 'Replete?'... ");
                },
                $type: 'parallel',
                states: [
                    { // Empty state generated by BPMNer and supported by scion.js...
                    },
                    {
                        states: [
                            {
                                id: 'End@End',
                                transitions: [
                                    {
                                        event: 'yes_',
                                        target: 'End'
                                    }
                                ]
                            },
                            {
                                id: 'End'
                            }
                        ]
                    }
                ],
                transitions: [
                    {
                        event: 'no_',
                        target: 'Hungry_'
                    }
                ]
            }
        ]
    }
);

cycle.start();
cycle.gen('go!');
console.log("'go!' sent: " + cycle.getConfiguration());
cycle.gen('no_');
console.log("'no_' sent: " + cycle.getConfiguration());
